enum Interests {
  outdoorActivities('Outdoors'),
  hiking('Hiking'),
  biking('Biking'),
  running('Running'),
  swimming('Swimming'),
  skateboarding('Skateboarding'),
  skiing('Skiing'),
  snowboarding('Snowboarding'),
  surfing('Surfing'),
  camping('Camping'),
  rockClimbing('Rock-Climbing'),
  hunting('Hunting'),
  fishing('Fishing'),
  boating('Boating'),
  kayaking('Kayaking'),
  birdwatching('Birdwatching'),
  stargazing('Stargazing'),
  sportsAndFitness('Sports and Fitness'),
  yoga('Yoga'),
  pilates('Pilates'),
  powerlifting('Powerlifting'),
  bodybuilding('Bodybuilding'),
  martialArts('Martial-Arts'),
  tennis('Tennis'),
  golf('Golf'),
  creativeArts('Creative-Arts'),
  photography('Photography'),
  cinematography('Cinematography'),
  art('Art'),
  writing('Writing'),
  makingMusic('Making-Music'),
  painting('Painting'),
  sculpting('Sculpting'),
  dance('Dance'),
  travelAndExploration('Travel and Exploration'),
  domesticTravel('Domestic-Travel'),
  internationalTravel('International-Travel'),
  beach('Beach'),
  backpacking('Backpacking'),
  culturalImmersion('Cultural Immersion'),
  foodAndDrink('Food-and-Drink'),
  cooking('Cooking'),
  bbq('BBQ'),
  food('Food'),
  adultBeverages('Adult-Beverages'),
  wineTasting('Wine-Tasting'),
  craftBeerBrewing('Craft Beer Brewing'),
  hobbiesAndCrafts('Hobbies and Crafts'),
  gardening('Gardening'),
  sewing('Sewing'),
  knitting('Knitting'),
  crocheting('Crocheting'),
  woodworking('Woodworking'),
  pottery('Pottery'),
  scrapbooking('Scrapbooking'),
  technologyAndGaming('Technology and Gaming'),
  coding('Coding'),
  gaming('Gaming'),
  virtualReality('Virtual-Reality'),
  printing3D('3D-Printing'),
  robotics('Robotics'),
  entertainment('Entertainment'),
  concerts('Concerts'),
  raves('Raves'),
  movies('Movies'),
  theater('Theater'),
  standUpComedy('Stand-Up Comedy'),
  readingAndLearning('Reading and Learning'),
  reading('Reading'),
  personalDevelopment('Personal Development'),
  languageLearning('Language-Learning'),
  history('History'),
  science('Science'),
  gamesAndStrategy('Games and Strategy'),
  chess('Chess'),
  casinoGames('Casino-Games'),
  boardGames('Board-Games'),
  escapeRooms('Escape-Rooms'),
  puzzles('Puzzles'),
  vehiclesAndTransportation('Vehicles and Transportation'),
  motorcycles('Motorcycles'),
  cars('Cars'),
  cycling('Cycling'),
  restorationOfVintageVehicles('Restoration of Vintage Vehicles'),
  natureAndAnimals('Nature and Animals'),
  pets('Pets'),
  mushrooming('Mushrooming'),
  animalRescue('Animal-Rescue'),
  conservation('Conservation'),
  beekeeping('Beekeeping');

  final String value;
  const Interests(this.value);

  @override
  String toString() => value;
}
