// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ1lzjfR81kfNC-KszsF2xmct0oCYgMRU',
    appId: '1:360184712841:web:2ab32cabc9c18688c3c058',
    messagingSenderId: '360184712841',
    projectId: 'nomo-app-c3417',
    authDomain: 'nomo-app-c3417.firebaseapp.com',
    storageBucket: 'nomo-app-c3417.appspot.com',
    measurementId: 'G-229FE4130L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcUcn0I6laadIBXwFwCOaDyPlSe89mMZA',
    appId: '1:360184712841:android:766cdb4333a41438c3c058',
    messagingSenderId: '360184712841',
    projectId: 'nomo-app-c3417',
    storageBucket: 'nomo-app-c3417.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu86mZPXFGOKreKxW_yTh1zXU0dIWNkSQ',
    appId: '1:360184712841:ios:850e607150511588c3c058',
    messagingSenderId: '360184712841',
    projectId: 'nomo-app-c3417',
    storageBucket: 'nomo-app-c3417.appspot.com',
    iosBundleId: 'com.example.nomoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu86mZPXFGOKreKxW_yTh1zXU0dIWNkSQ',
    appId: '1:360184712841:ios:850e607150511588c3c058',
    messagingSenderId: '360184712841',
    projectId: 'nomo-app-c3417',
    storageBucket: 'nomo-app-c3417.appspot.com',
    iosBundleId: 'com.example.nomoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ1lzjfR81kfNC-KszsF2xmct0oCYgMRU',
    appId: '1:360184712841:web:5da087e6d2e289b1c3c058',
    messagingSenderId: '360184712841',
    projectId: 'nomo-app-c3417',
    authDomain: 'nomo-app-c3417.firebaseapp.com',
    storageBucket: 'nomo-app-c3417.appspot.com',
    measurementId: 'G-VZMFRDZNBF',
  );

}